# Generated by Django 5.0.14 on 2026-07-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendationlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="recommendationlog",
            name="payload",
            field=models.JSONField(
                help_text="Contenu : {'recommended_product_ids': [...]}"
            ),
        ),
    ]
