# Generated by Django 5.0.14 on 2026-09-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_unique_delivery_per_order(apps, schema_editor):
    Delivery = apps.get_model('orders', 'Delivery')
    duplicates = list(
        Delivery.objects.values('order_id')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('order_id', flat=True)[:10]
    )
    if duplicates:
        raise RuntimeError(
            'Migration interrompue : plusieurs livraisons existent pour les commandes '
            f'{duplicates}. Rapprochez-les avant de relancer.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_inventory_variant_alter_product_store_and_more'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_status',
            field=models.CharField(choices=[('none', 'Aucune réservation'), ('reserved', 'Réservé'), ('committed', 'Déduit'), ('released', 'Libéré')], default='none', max_length=20),
        ),
        migrations.RunPython(
            assert_unique_delivery_per_order,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.store'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant'),
        ),
    ]
