# Generated by Django 5.2.17 on 2026-09-05 13:50

from django.db import migrations, models
from django.db.models import Count


def assert_valid_order_items(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    invalid = list(
        OrderItem.objects.filter(quantity__lte=0).values_list('pk', flat=True)[:10]
    )
    duplicates = list(
        OrderItem.objects.values('order_id', 'product_variant_id')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('order_id', 'product_variant_id')[:10]
    )
    if invalid or duplicates:
        raise RuntimeError(
            'Migration interrompue : lignes de commande invalides. '
            f'Quantités non positives={invalid}; couples commande/variante dupliqués={duplicates}. '
            'Corrigez-les après rapprochement métier.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_inventory_inventory_quantity_nonnegative_and_more"),
        ("orders", "0003_order_stock_status_alter_delivery_order_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assert_valid_order_items,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="order_item_positive_quantity",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product_variant"), name="order_variant_unique"
            ),
        ),
    ]
