# Generated by Django 5.0.14 on 2026-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="minio_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
