# Generated by Django 5.0.14 on 2026-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_store_latitude_store_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
    ]
