# Generated by Django 5.0.14 on 2026-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_store_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="stores/banners/"),
        ),
    ]
