# Generated by Django 5.0.14 on 2026-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_store_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
