# Generated by Django 5.0.14 on 2026-09-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_unique_inventory_per_variant(apps, schema_editor):
    Inventory = apps.get_model('catalog', 'Inventory')
    duplicates = list(
        Inventory.objects.values('variant_id')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('variant_id', flat=True)[:10]
    )
    if duplicates:
        raise RuntimeError(
            'Migration interrompue : plusieurs inventaires existent pour les variantes '
            f'{duplicates}. Fusionnez-les explicitement avant de relancer.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_store_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            assert_unique_inventory_per_variant,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.store'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
