# Generated by Django 5.2.17 on 2026-09-05 13:50

from django.db import migrations, models
from django.db.models import F, Q


def assert_valid_inventory_quantities(apps, schema_editor):
    Inventory = apps.get_model('catalog', 'Inventory')
    invalid = list(
        Inventory.objects.filter(
            Q(quantity__lt=0)
            | Q(reserved_quantity__lt=0)
            | Q(reserved_quantity__gt=F('quantity'))
        ).values_list('pk', flat=True)[:10]
    )
    if invalid:
        raise RuntimeError(
            'Migration interrompue : quantités ou réservations d’inventaire invalides '
            f'pour {invalid}. Corrigez ces stocks après rapprochement métier.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_inventory_variant_alter_product_store_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assert_valid_inventory_quantities,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="inventory_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)),
                name="inventory_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", models.F("reserved_quantity"))),
                name="inventory_covers_reservations",
            ),
        ),
    ]
