# Generated by Django 5.0.14 on 2026-07-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0004_alter_subscription_status"),
        ("orders", "0002_initial"),
        ("payments", "0002_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="monetization.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payee_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("order__isnull", False), ("subscription__isnull", True)),
                    models.Q(("order__isnull", True), ("subscription__isnull", False)),
                    _connector="OR",
                ),
                name="payment_targets_order_xor_subscription",
            ),
        ),
    ]
