# Generated by Django 5.0.14 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_subscription_alter_payment_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                    ("card", "Carte bancaire"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_ref",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
