# Generated by Django 5.0.14 on 2026-09-04

from django.db import migrations, models
from django.db.models import Count


def assert_unique_payment_per_order(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    duplicates = list(
        Payment.objects.exclude(order_id=None)
        .values('order_id')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('order_id', flat=True)[:10]
    )
    if duplicates:
        raise RuntimeError(
            'Migration interrompue : plusieurs paiements existent pour les commandes '
            f'{duplicates}. Rapprochez-les avant de relancer.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_add_naboopay_checkout"),
    ]

    operations = [
        migrations.RunPython(
            assert_unique_payment_per_order,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
