# Generated by Django 5.0.14 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_add_naboopay_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
