# Generated by Django 5.0.14 on 2026-09-04 23:02

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def assert_unique_payment_references(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    duplicate_subscriptions = list(
        Payment.objects.exclude(subscription_id=None)
        .values('subscription_id')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('subscription_id', flat=True)[:10]
    )
    duplicate_provider_refs = list(
        Payment.objects.exclude(provider_ref='')
        .values('provider_ref')
        .annotate(total=Count('pk'))
        .filter(total__gt=1)
        .values_list('provider_ref', flat=True)[:10]
    )
    if duplicate_subscriptions or duplicate_provider_refs:
        raise RuntimeError(
            'Migration interrompue : paiements dupliqués. '
            f'Abonnements={duplicate_subscriptions}; références fournisseur={duplicate_provider_refs}. '
            'Rapprochez-les avant de relancer.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0006_set_plan_product_limits'),
        ('orders', '0003_order_stock_status_alter_delivery_order_and_more'),
        ('payments', '0005_protect_order_payment'),
    ]

    operations = [
        migrations.RunPython(
            assert_unique_payment_references,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='monetization.subscription'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.payment'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider_ref',), name='payment_provider_ref_unique_when_present'),
        ),
    ]
