# Generated by Django 5.0.14 on 2026-09-04

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_subscription_alter_refund_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(db_index=True, default=apps.payments.models.payment_expiry),
        ),
    ]
