# Generated by Django 5.0.14 on 2026-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
