# Generated by Django 5.0.14 on 2026-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0003_notification_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
