# Generated by Django 5.0.14 on 2026-07-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0004_alter_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_products",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
