# Generated by Django 5.2.17 on 2026-09-05 13:50

from django.db import migrations, models


def assert_positive_cart_quantities(apps, schema_editor):
    CartItem = apps.get_model('shopping', 'CartItem')
    invalid = list(
        CartItem.objects.filter(quantity__lte=0).values_list('pk', flat=True)[:10]
    )
    if invalid:
        raise RuntimeError(
            'Migration interrompue : quantités de panier non positives pour '
            f'{invalid}. Corrigez ou retirez ces lignes avant de relancer.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_inventory_inventory_quantity_nonnegative_and_more"),
        ("shopping", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(
            assert_positive_cart_quantities,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="cart_item_positive_quantity",
            ),
        ),
    ]
